"use client";
import { useState } from "react";
import { ArrowRight, BedDouble, Bell, Building2, CalendarClock, Check, ChevronRight, HeartHandshake, Home, MapPin, Phone, Plus, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type View="today"|"handoffs"|"care";
const cases=[
  {name:"M. Carter",need:"Memory care",when:"Today, 4:00 PM",status:"We’re calling homes",urgent:true},
  {name:"R. Williams",need:"Adult family home",when:"Tomorrow",status:"3 homes reviewing"},
  {name:"A. Lee",need:"Assisted living",when:"Sep 14",status:"Options ready"},
];
const homes=[
  {name:"Cedar Grove Adult Family Home",distance:"2.4 mi",beds:2,tags:["Medicaid","Memory care","Hoyer lift"]},
  {name:"Northlake Senior Living",distance:"4.8 mi",beds:1,tags:["Private pay","Memory care","Hospice"]},
  {name:"Harbor View Care Residence",distance:"7.1 mi",beds:3,tags:["Medicaid","Wound care","Behavioral"]},
];

export function PreviousDesk(){
  const [view,setView]=useState<View>("today"),[handoff,setHandoff]=useState(false),[detail,setDetail]=useState<(typeof cases)[number]|null>(null),[home,setHome]=useState<(typeof homes)[number]|null>(null),[medicaid,setMedicaid]=useState(false),[notice,setNotice]=useState("");
  const done=(text:string)=>{setHandoff(false);setHome(null);setNotice(text);setView("today")};
  return <div className="min-h-screen bg-[#f5f7f6] text-slate-950">
    <header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b bg-white/95 px-4 backdrop-blur lg:px-6">
      <span className="flex size-9 items-center justify-center rounded-xl bg-teal-700 text-white"><HeartHandshake className="size-5"/></span>
      <div><p className="text-sm font-semibold">Care Transition Desk</p><p className="hidden text-xs text-slate-500 sm:block">Elderly Care Match</p></div>
      <Badge variant="outline" className="hidden border-amber-200 bg-amber-50 text-amber-800 md:flex">Prototype · sample data</Badge>
      <div className="ml-auto flex gap-2"><Button variant="outline" className="hidden md:flex"><Phone/> Urgent help</Button><Button variant="ghost" size="icon"><Bell/></Button><Button onClick={()=>setHandoff(true)}><Plus/><span className="hidden sm:inline">Hand off a case</span><span className="sm:hidden">New handoff</span></Button></div>
    </header>
    <div className="flex">
      <aside className="sticky top-16 hidden h-[calc(100vh-4rem)] w-60 border-r bg-white p-3 lg:block">
        <p className="px-3 py-3 text-[11px] font-semibold uppercase tracking-widest text-slate-400">Your workspace</p>
        <Nav active={view==="today"} icon={Home} label="Today" onClick={()=>setView("today")}/><Nav active={view==="handoffs"} icon={HeartHandshake} label="My handoffs" onClick={()=>setView("handoffs")}/><Nav active={view==="care"} icon={BedDouble} label="Browse care" onClick={()=>setView("care")}/>
        <div className="absolute bottom-4 left-3 right-3 rounded-xl border border-teal-200 bg-teal-50 p-4"><p className="font-semibold">A case can’t wait?</p><p className="my-2 text-xs">Call us. We’ll take it from there.</p><Button size="sm" className="w-full"><Phone/> (206) 555-0144</Button></div>
      </aside>
      <main className="min-w-0 flex-1 px-4 pb-24 pt-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
        {notice&&<div className="mb-5 flex gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><Check className="size-4"/>{notice}</div>}
        {view==="today"&&<Today open={()=>setHandoff(true)} detail={()=>setDetail(cases[0])} care={()=>setView("care")}/>} {view==="handoffs"&&<Handoffs open={()=>setHandoff(true)} detail={setDetail}/>} {view==="care"&&<Care medicaid={medicaid} toggle={()=>setMedicaid(!medicaid)} options={medicaid?homes.filter(h=>h.tags.includes("Medicaid")):homes} select={setHome}/>} 
      </div></main>
    </div>
    <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-4 border-t bg-white p-2 lg:hidden"><Mobile active={view==="today"} icon={Home} label="Today" click={()=>setView("today")}/><Mobile active={view==="handoffs"} icon={HeartHandshake} label="Handoffs" click={()=>setView("handoffs")}/><Mobile primary icon={Plus} label="Hand off case" click={()=>setHandoff(true)}/><Mobile active={view==="care"} icon={BedDouble} label="Browse care" click={()=>setView("care")}/></nav>
    <Handoff open={handoff} close={()=>setHandoff(false)} done={()=>done("Handoff received. Your advisor will call the family and update you within 15 minutes.")}/><CaseDetail item={detail} close={()=>setDetail(null)}/><HomeCheck item={home} close={()=>setHome(null)} done={()=>done("Your advisor is checking this home. Nothing else is needed from you.")}/>
  </div>}

function Head({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Thursday, September 10</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-slate-600">{text}</p></div>{action}</div>}
function Today({open,detail,care}:{open:()=>void;detail:()=>void;care:()=>void}){return <><Head title="Good morning, Jamie" text="We’re working three handoffs. You only need to look at what’s marked for you." action={<Button onClick={open}><Plus/> Hand off a case</Button>}/><section className="mb-6 overflow-hidden rounded-xl border border-red-200 bg-white"><div className="flex flex-col gap-4 bg-red-50 p-5 sm:flex-row sm:items-center"><CalendarClock className="text-red-700"/><div className="flex-1"><h2 className="font-semibold">M. Carter discharges today <Badge className="bg-red-600">We’re on it</Badge></h2><p className="text-sm text-slate-600">Your advisor is calling matching homes. Next update by 10:30 AM.</p></div><Button onClick={detail} className="bg-red-700">See progress <ArrowRight/></Button></div><div className="grid sm:grid-cols-3"><Stat n="0" a="Needs you" b="Nothing right now"/><Stat n="2" a="We’re handling" b="Active searches"/><Stat n="1" a="Options ready" b="Family reviewing"/></div></section><div className="grid gap-6 xl:grid-cols-[1.5fr_.7fr]"><List detail={d=>d&&detail()}/><section className="rounded-xl bg-slate-950 p-5 text-white"><HeartHandshake className="text-teal-300"/><h2 className="mt-4 font-semibold">A 60-second handoff</h2><p className="mt-2 text-sm leading-6 text-slate-300">Give us discharge timing and a family contact. We gather everything else and call homes.</p><Button onClick={open} className="mt-5 w-full justify-between bg-teal-400 text-slate-950">Hand off a case <ArrowRight/></Button></section></div><button onClick={care} className="mt-6 flex w-full items-center justify-between rounded-xl border bg-white p-5 text-left"><div><b>Want to browse available care?</b><p className="text-sm text-slate-500">Optional. Your advisor handles fit checks and outreach.</p></div><ChevronRight/></button></>}
function Handoffs({open,detail}:{open:()=>void;detail:(x:(typeof cases)[number])=>void}){return <><Head title="Your handoffs" text="See what we’re doing, what happens next, and whether we need anything from you." action={<Button onClick={open}><Plus/> Hand off a case</Button>}/><div className="mb-4 flex gap-2 rounded-xl border bg-white p-3"><Input placeholder="Search a handoff"/><Button variant="outline">Needs me</Button></div><List detail={detail}/></>}
function List({detail}:{detail:(x:(typeof cases)[number])=>void}){return <section className="overflow-hidden rounded-xl border bg-white">{cases.map(c=><button key={c.name} onClick={()=>detail(c)} className="grid w-full grid-cols-[1fr_auto] items-center gap-4 border-t p-4 text-left first:border-0 sm:grid-cols-[1fr_1fr_1fr_auto]"><div><b>{c.name}</b><p className="text-xs text-slate-500">{c.need}</p></div><span className={c.urgent?"text-sm font-semibold text-red-700":"hidden text-sm sm:block"}>{c.when}</span><Badge variant="outline" className="hidden sm:flex">{c.status}</Badge><ChevronRight/></button>)}</section>}
function Care({options,medicaid,toggle,select}:{options:typeof homes;medicaid:boolean;toggle:()=>void;select:(x:(typeof homes)[number])=>void}){return <><Head title="Browse available care" text="Optional: flag a promising home and your advisor will check fit, availability, and payment."/><div className="mb-5 flex gap-2 rounded-xl border bg-white p-4"><Button variant={medicaid?"default":"outline"} onClick={toggle}>{medicaid&&<Check/>} Accepts Medicaid</Button><Badge variant="secondary" className="ml-auto">{options.length} available</Badge></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{options.map(h=><section key={h.name} className="rounded-xl border bg-white p-5"><div className="flex justify-between"><Building2/><Badge className="bg-emerald-100 text-emerald-800">{h.beds} beds now</Badge></div><h2 className="mt-4 font-semibold">{h.name}</h2><p className="text-xs text-slate-500"><MapPin className="inline size-3"/> {h.distance}</p><div className="my-4 flex flex-wrap gap-1">{h.tags.map(t=><Badge key={t} variant="secondary">{t}</Badge>)}</div><Button onClick={()=>select(h)} className="w-full">Ask our team about this home</Button></section>)}</div></>}

function Handoff({open,close,done}:{open:boolean;close:()=>void;done:()=>void}){const[timing,setTiming]=useState("Today — urgent"),[initials,setInitials]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState("");const ready=initials.trim()&&name.trim()&&phone.replace(/\D/g,"").length>=10;return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="max-h-[92vh] overflow-y-auto p-0 sm:max-w-xl"><DialogHeader className="border-b p-5"><Badge className="mb-2 bg-teal-100 text-teal-800">About 60 seconds · 4 quick answers</Badge><DialogTitle>Hand off a case</DialogTitle><DialogDescription>We collect the details, confirm authorization, contact homes, and keep you updated.</DialogDescription></DialogHeader><div className="space-y-5 p-5"><p className="rounded-xl bg-teal-50 p-4 text-sm"><b>You are not doing our intake.</b> Share only what you already know.</p><Field label="When is discharge?"><div className="grid grid-cols-2 gap-2">{["Today — urgent","Tomorrow","Within a week","Planning ahead"].map(x=><button key={x} onClick={()=>setTiming(x)} className={`min-h-11 rounded-xl border px-3 text-left text-sm ${timing===x?"border-teal-700 bg-teal-50 ring-1 ring-teal-700":""}`}>{x}{timing===x&&<Check className="float-right size-4"/>}</button>)}</div></Field><Field label="Patient initials"><Input value={initials} onChange={e=>setInitials(e.target.value)} placeholder="e.g. M.C."/></Field><section className="rounded-xl border p-4"><b><Phone className="mr-2 inline size-4"/>Who can we call to discuss options?</b><p className="mb-3 text-xs text-slate-500">Usually family, legal representative, or patient.</p><div className="grid gap-3 sm:grid-cols-2"><Field label="Contact name"><Input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Phone"><Input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(206) 555-0123"/></Field></div></section><Field label="Anything we should know? (optional)"><Textarea placeholder="One sentence is enough."/></Field><p className="rounded-xl bg-slate-50 p-4 text-xs">✓ We call the family &nbsp; ✓ We confirm authorization &nbsp; ✓ We contact homes</p></div><footer className="sticky bottom-0 border-t bg-white p-4 shadow-lg"><Button disabled={!ready} onClick={done} className="h-11 w-full">Hand off to our team <ArrowRight/></Button>{!ready&&<p className="mt-2 text-center text-xs text-slate-500">Add initials and a contact number to continue.</p>}</footer></DialogContent></Dialog>}
function CaseDetail({item,close}:{item:(typeof cases)[number]|null;close:()=>void}){return <Dialog open={!!item} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><Badge className="mb-2 bg-red-100 text-red-800">{item?.when}</Badge><DialogTitle>{item?.name}</DialogTitle><DialogDescription>No placement work is waiting on you.</DialogDescription></DialogHeader><p className="rounded-xl bg-emerald-50 p-4 text-sm"><b>Nothing needed from you right now.</b> We’ll alert you only if needed.</p>{["Family reached","Matching homes contacted","Options coming next"].map((x,i)=><div key={x} className="flex gap-3"><span className="flex size-7 items-center justify-center rounded-full bg-teal-700 text-white">{i<2?<Check className="size-4"/>:"3"}</span><div><b className="text-sm">{x}</b><p className="text-xs text-slate-500">{i===2?"Next update by 10:30 AM.":"Completed by your advisor."}</p></div></div>)}</DialogContent></Dialog>}
function HomeCheck({item,close,done}:{item:(typeof homes)[number]|null;close:()=>void;done:()=>void}){return <Dialog open={!!item} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>Ask our team about this home</DialogTitle><DialogDescription>You don’t need to call or send records. Your advisor checks fit and availability.</DialogDescription></DialogHeader><p className="rounded-xl border p-4"><b>{item?.name}</b><br/><small>{item?.distance} · {item?.beds} beds reported</small></p><p className="flex gap-2 rounded-xl bg-blue-50 p-3 text-xs"><ShieldCheck className="size-4"/>No information is shared automatically.</p><Button onClick={done}>Ask advisor to check</Button></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Stat({n,a,b}:{n:string;a:string;b:string}){return <div className="border-t p-4 sm:border-r"><b className="text-xl">{n}</b><p className="text-xs font-medium">{a}</p><p className="text-xs text-slate-500">{b}</p></div>}
function Nav({icon:I,label,active,onClick}:{icon:typeof Home;label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`mb-1 flex w-full gap-3 rounded-lg px-3 py-2.5 text-sm ${active?"bg-teal-50 font-medium text-teal-800":"text-slate-600"}`}><I className="size-4"/>{label}</button>}
function Mobile({icon:I,label,active,primary,click}:{icon:typeof Home;label:string;active?:boolean;primary?:boolean;click:()=>void}){return <button onClick={click} className={`flex flex-col items-center text-[10px] ${active?"text-teal-700":"text-slate-500"}`}><span className={`flex size-8 items-center justify-center rounded-lg ${primary?"bg-teal-700 text-white":""}`}><I className="size-4"/></span>{label}</button>}
